### PR TITLE
Scroll Setting UX update

### PR DESCRIPTION
**Pull request by stulees**
- "section" container and `<h5>` removed
- layout revised to be a horizontal 3 column grid, collapse to 1 column below medium size
- labels have `.control-label` applied for appropriate styling
- tests referring to deprecated `.more-scroll-options` class removed
- version bump

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Please review, thanks.

**Comment by donnapep** [comment]
@stulees Where can I find the new UX for this?

**Comment by stulees** [comment]
@donnapep I realized yesterday that Mat didn't use Scroll Setting and instead provided Transition and Transition Hold. We spoke yesterday and he agreed it should be Scroll Setting and that I would update the markup to be horizontal 3 column grid. Have a look to http://ux-design.s3.amazonaws.com/widgets-ui/prototypes/widgets-ui/index.html and the Transition / Transition Hold for reference. This is where Scroll Setting will be used.

**Comment by donnapep** [comment]
@stulees Think I got it. So it will be Transition, Speed and then Transition Hold in one row, and Speed and Pause will only show if Transition is not None, correct? If so, :+1:

**Comment by stulees** [comment]
@donnapep Actually Scroll Setting is to replace where you see Transition and Transition Hold. Those transition settings are settings that Mat took from the old Gadget. Those settings evolved into our current Scroll Setting component. 

As far as transition goes, we spoke about that and if "None" is chosen from Scroll Setting, then by default items will fade in and out.

**Comment by donnapep** [comment]
@stulees OK, wasn't sure of the labels since those are defined in `common-i18n` and I didn't bother to check them there. :+1:

**Pull request merged**
