### PR TITLE
Remove font-style and url-field components

### PR DESCRIPTION
**Pull request by donnapep**
* Not removing `alignment` component as its used in both `column-setting` and `table-setting`.
* `font-style` and `url-field` are used in old versions of the `font-setting` component. Removing these as we would have to migrate to the latest version of `font-setting` if changes were needed to either of these components.

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review. Thx.

**Comment by stulees** [comment]
@donnapep :+1: So I guess this means we need to continue supporting the non-angular tests and the use of CasperJS, correct?

**Comment by donnapep** [comment]
@stulees Yes, but I think once we rewrite Spreadsheet and Financial Table we'll be able to get rid of the alignment component and therefore CasperJS.

**Comment by stulees** [comment]
@donnapep Sounds good

**Pull request merged**
