### PR TITLE
Set column-setting default value for numeric field

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review. Thx.

**Comment by stulees** [comment]
@donnapep Can you clarify the changes to the `font-setting` tests?

**Comment by donnapep** [comment]
@stulees Apparently Google Fonts API released some additional fonts, which broke some of the tests. I tried to pick fonts that were higher up in the dropdown list so hopefully less tests break if this should happen again.

**Comment by stulees** [comment]
@donnapep 👍  Okay thanks for clarifying

**Pull request closed without merging**
