### PR TITLE
Move custom font selection to top of dropdown

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review. Thx.

**Comment by stulees** [comment]
@donnapep This will need a rebase now that I've merged mine and also I think you can remove the version bump as we can just keep the one from mine.

**Comment by donnapep** [comment]
@stulees OK, I've rebased. Thx.

**Comment by stulees** [comment]
@donnapep :+1: I can take updating Time & Date widget after you merge and release this, thanks.

**Comment by donnapep** [comment]
@stulees Thanks! You're good to go.

**Pull request merged**
