### PR TITLE
Removed layout classes (row and col) from the background

### PR DESCRIPTION
**Pull request by rodrigopavezi**
image settings widget so it can use the css from
the parent app

@stulees @donnapep could you please review? cheers

### CODE REVIEW

**Comment by stulees** [comment]
@rodrigopavezi Will this have any impact on existing uses of Background Image Setting? There is one Widget currently using it (Web Page Widget).

**Comment by rodrigopavezi** [comment]
@stulees yes, it will. I thought you said that no one was using it the time I changed it before. So I went and changed it without caring about back compatibility. Now, I wonder how should we approach. We need to remove this classes as they don't play nice with parents css. Do you have any suggestion? cheers

**Comment by stulees** [comment]
@rodrigopavezi Yes the Web Page Widget was overlooked, it uses it, however I've also noticed you've removed Position Settings classes as well. Position Setting is used in several Widgets. These components were developed to work in the existing Widget Settings UX.

I think if you're looking to use components from this repo outside the context of a Widget settings and the layout/css doesn't work in the way you need it to, then you may need to produce a different version elsewhere. Is this a possibility?

**Comment by ghislaineguerin** [comment]
@rodrigopavezi @stulees Isn't it better to remove those row classes from there and modify the css so it continues working on web widget but we add a class there for that. Don't think we should have a copy just for different layout.

**Comment by stulees** [comment]
@ghislaineguerin The components in this repo are Angular custom directives, when used elsewhere, the layout/css is not accessible. Also, the classes being removed are Bootstrap classes which all of the components in this repo use for appropriate sizing of elements in the widget settings form. I'm not sure I follow how we can add a specific class to the instance used in Web Page Widget or all Widgets where Position Setting is used. Can you clarify?

**Comment by ghislaineguerin** [comment]
@stulees I just tried modifying styles for this component and css changes do affect it. So I would recommend removing the layout classes and add conditional styling for when this component it shown inside widget settings, inside the sidebar and for modal like in presentation settings.

**Comment by stulees** [comment]
@ghislaineguerin Okay, conditionally adding styling sounds like the best solution here. Thanks

@rodrigopavezi How about adding a new optional attribute to both Background Setting and Position Setting components where the value of it determines what classes should be applied. It would be best if by default the attribute is not required and it defaults on applying the current classes so that nothing has to change in our existing Widgets that use these components. Sound okay?

**Comment by rodrigopavezi** [comment]
@stulees @ghislaineguerin sounds like it is an awesome solution. I will make the changes. cheers

**Comment by rodrigopavezi** [comment]
@stulees I have made the change, could you please review? cheers
@ghislaineguerin FYI.

**Comment by stulees** [comment]
@rodrigopavezi Looks good, thanks! I don't see any tests towards ensuring the right class names are applied based on the new attributes though, can you add any?

**Comment by rodrigopavezi** [comment]
@stulees good point, I will add some. cheers.

**Comment by rodrigopavezi** [comment]
@stulees I made the changes, could you please review? cheers

**Comment by stulees** [comment]
@rodrigopavezi :+1: Can you squash your commits, thanks!

**Pull request merged**
