### PR TITLE
fixed image load and appearance on the background

### PR DESCRIPTION
**Pull request by rodrigopavezi**
image settings widget component.

@stulees @donnapep could you please review? I have changed it so it can load and show the image right after changing the URL.

You can see it working on the new editor deployed to https://editor-stage-0.risevision.com/#/editor/workspace/932a85ed-ddb4-4ac0-bd3c-431804c659a0?cid=b428b4e8-c8b9-41d5-8a10-b4193c789443

Click on the cog icon on the toolbar at the top.

cheers

### CODE REVIEW

**Comment by stulees** [comment]
@rodrigopavezi Just needs a version bump, thanks

**Comment by rodrigopavezi** [comment]
@stulees version bumped. please review. cheers

**Comment by stulees** [comment]
@rodrigopavezi :+1:

**Comment by rodrigopavezi** [comment]
@stulees thanks a mill!!

**Pull request merged**
