### PR TITLE
Changed it to use original angular-bootstrap-colorpicker

### PR DESCRIPTION
**Pull request by rodrigopavezi**
@stulees please review.
@ghislaineguerin FYI.

cheers

### CODE REVIEW

**Comment by stulees** [comment]
@rodrigopavezi We should specify the latest minor-patch tag instead of pointing directly to the repo. So `"angular-bootstrap-colorpicker": "~3.0.19"`

**Comment by rodrigopavezi** [comment]
@stulees good point, I will make the change. cheers

**Comment by rodrigopavezi** [comment]
@stulees could I merge this one? cheers

**Comment by stulees** [comment]
@rodrigopavezi Going to need a minor version bump first, then a new release after merging. Otherwise looks good.

**Comment by rodrigopavezi** [comment]
@stulees sorry, I thought I had already done the version bumping but I guess I did on the old PR. I will do cheers.

**Pull request closed without merging**
