### PR TITLE
Font Setting and URL Field updates, Angular 1.3, css gulp tasks removed

### PR DESCRIPTION
**Pull request by stulees**
- bower
	- Upgrading angular and angular-mocks to `1.3`
	- common-style dependency changed to pull in latest release, but will resolve to tag `1.2.3`
- npm packages revised and removed all unnecessary ones
- gulp file
	- all css related tasks removed
	- var references to gulp modules no longer needed removed
- component updates
	- URL Field directive HTML updated to remove tooltip and remove default checked state
	- URL Field e2e tests revised
	- Font Setting directive HTML updated to adhere to new UX styling
- all e2e test HTML pages updated to apply new UX markup that will be used in a Widget Settings page
- distributed versions of angular directives include minimal changes from the build due to upgrade of Angular to `1.3`, not causing any issues
- version bump to `0.1.13`

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Please review, thanks

**Comment by donnapep** [comment]
@stulees So the URL field validation checkbox essentially does the opposite of what it was doing before, correct? Won't this cause problems when we update existing Widgets to use this new version?

**Comment by stulees** [comment]
@donnapep No, it won't cause problems. The `ng-click` directive value did not change, it still performs `"doValidation = !doValidation"` and `doValidation` still by default is initialized with a value of `true`.  The only difference is the checkbox now starts unchecked as opposed to checked (and the translation is different). So when the URL Field is shown in a Settings of an existing Widget with a URL value, clicking the checkbox performs the same logic.

**Comment by donnapep** [comment]
@stulees To confirm, this is not a setting that is saved in the Presentation, correct? I can't recall. If so, this is fine. :+1:

**Comment by stulees** [comment]
@donnapep Correct, the only value saved in a presentation settings associated with the URL Field directive is `url`.

**Pull request merged**
