### PR TITLE
[URL Field] Adding file type feature

### PR DESCRIPTION
**Pull request by stulees**
- html template updated to conditionally apply an error message
- directive updated to include a `fileType` attribute and now validate a proper file extension if fileType has been used
-  test html updated to use several different instances of `<url-field>` to expand better e2e tests
- e2e tests revised and reorganized into sections pertaining to different instances of the `<url-field>`, additional tests added also against the new file type functionality
- demo updated
- bower updated to force the master branch of `rv-common-i18n` to be used
- version bump

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Note that I'm now forcing the `master` branch of `rv-common-i18n` to be used (includes a resolution). This is the only way to get this repo to use the latest translations, otherwise we'll have to continuously change the tag to point to. I've also version bumped and will tag this as a new release after it's merged. Please review, thanks.

**Comment by donnapep** [comment]
@stulees Why not use the `hasValidExtension` function in the `imageValidator` service for validating an image URL instead?

**Comment by stulees** [comment]
@donnapep I had initially started to use that but decided against it. It will require adding `widget-settings-ui-core` as a dependency to this repo, which when I did, there were conflicts regarding `angular-translate` and resolutions would be required. Also, I'm somewhat trying to allow for URL Field to be used outside a widget settings. In that scenario, `widget-settings-ui-core` will need importing so that the `imageValidator` service is found. 

I prefer to keep this small function encapsulated within URL Field itself. It can mean `hasValidExtension` can be removed from `imageValidator` as I don't think it will ever be needed since URL Field handles it. Thanks

**Comment by donnapep** [comment]
@stulees In this instance, I tend to agree. I'll remove that function after I've updated Image Widget. This may come up again later and we'll have to take another look at it at that time. :+1:

**Comment by stulees** [comment]
@donnapep Cheers

**Pull request merged**
