### PR TITLE
Add support for custom fonts to font selector

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@rodrigopavezi @stulees I'm stuck on how to disable the `Select` button in the custom font modal if the URL field is empty or invalid. Any ideas? Thx.

**Comment by stulees** [comment]
@donnapep Shall we hold off reviewing for now since you think you might have figured out the issue?

**Comment by donnapep** [comment]
@stulees I'm getting closer. I'll let you know if I get stuck again. Thanks for asking.

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review. Thx.

**Comment by stulees** [comment]
@donnapep Just one question on an e2e test, otherwise looks good :+1:

**Pull request merged**
