### PR TITLE
[Background Image Setting] Adding new component

### PR DESCRIPTION
**Pull request by stulees**
- bower updated to use latest release of `rv-angular-bootstrap-colorpicker` and `common-style`
- directives and html template added
- e2e html and tests added
- test `.jpg` image added to accompany e2e tests
- demo added
- version bump

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep This is the new V2 version, being added as its own separate component to the existing Background Setting. Please review, thanks

**Comment by donnapep** [comment]
@stulees Having the version number in the name doesn't feel right. I know you already have another directive called `background-setting-image`, but I think we need a name similar to that to distinguish between them the old background setting and the new, rather than using a version #.

**Comment by stulees** [comment]
@donnapep Okay, instead of `-v2`, the only name I can come up with that stays relevant is `background-image-setting`. I wasn't thinking we would want "image" in the actual name though because using an image is optional. Best I can think of unless you have a better one? I can change the name of the helper directive to something shorter so it doesn't get confusing.

**Comment by donnapep** [comment]
@stulees The only thing I can think of would be to rename your helper to just `backgroundImage` and then use `backgroundSettingImage` for the component name.

**Comment by donnapep** [comment]
@stulees Re: not having image in the name. I think the name should be self-descriptive, so the fact that it supports images, although optional, `image` should probably be part of it.

**Comment by stulees** [comment]
@donnapep I prefer the other way around to be consistent with the other components, so I'll rename to `backgroundImageSetting` and will rename the helper to `backgroundImage`. Will get this changed and ready for review again shortly, thanks.

**Comment by stulees** [comment]
@donnapep Okay everything (file names, directive, tests, demo) has been changed to use the new name `background-image-setting` and the helper directive has been named to `background-image`. Can you review again, thanks.

**Comment by donnapep** [comment]
Yup, that looks good. :+1:

**Pull request merged**
