### PR TITLE
Removed storage selector from the URL filed component

### PR DESCRIPTION
**Pull request by rodrigopavezi**
@donnapep @stulees please review. cheers

### CODE REVIEW

**Comment by stulees** [comment]
@rodrigopavezi Changes look good, I think this needs a version bump though. Looks like there's problems with tests to sort out too. Thanks

**Comment by donnapep** [comment]
@rodrigopavezi Yup, needs a version bump. Otherwise :+1:

**Comment by rodrigopavezi** [comment]
@stulees @donnapep thanks. Version bumped.

**Comment by rodrigopavezi** [comment]
@stulees @donnapep what do you think about not releasing a version with this changes as it breaks the background image component. I think we can hold on this changes and merge and releases when everything is done. cheers

**Comment by donnapep** [comment]
@rodrigopavezi I think it's OK to hold for now, but once these changes go to validation the code should be complete and picking up the new version in bower.

**Comment by stulees** [comment]
@rodrigopavezi @donnapep I think holding off making a release is the right thing to do until all is ready/done. We can move the card to validation when it's at that point.

**Pull request merged**
