### PR TITLE
Add blur event and broadcast to listeners

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees I need the URL component to fire an event when it loses focus. Not sure if there's a better way to do this without broadcasting. Also, I versioned this repo and bumped the version in this PR.

Please review. Thx.

**Comment by stulees** [comment]
@donnapep What are you needing to do elsewhere that you need URL Field to fire an event when it loses focus? Also, you're using `$broadcast`, which dispatches an event name downwards to all child scopes. I think you're needing `$emit` instead unless I'm missing something. Thanks

**Comment by donnapep** [comment]
@stulees $emit won't call my controller handler, presumably because of the type of scope that URL field is using.

I need to do some validation in image widget to check that it is indeed an image. Trying to do it on every keystroke change to the URL was causing me no end of problems in the unit tests, and wasn't the most efficient method of doing this check regardless.

**Comment by stulees** [comment]
@donnapep I used a `$watch` on the `url` to check for a `.webm` file in Video Widget settings. See here - http://goo.gl/RpJSkC I don't quite follow as to what you are unit testing in this scenario, can you clarify?

**Comment by donnapep** [comment]
@stulees I followed that originally, but it's really problematic for what I need to do. I need to run the below async code when the URL changes, but I don't want to run it every time the user types a character into the URL field, which is what that code sample does. I think it should really only do that check when the URL loses its focus:

    function isImage(src) {
        var deferred = $q.defer(),
          image = new Image();

        image.onload = function() {
          deferred.resolve(true);
        };

        image.onerror = function() {
          deferred.resolve(false);
        };

        image.src = src;

        return deferred.promise;
      }

**Comment by stulees** [comment]
@donnapep Okay fair enough, but I think the use of `$broadcast` and `$rootScope` isn't the right approach. Not every instance of `<url-field>` should be using the `$rootScope` to `$broadcast` an event to all of its children with the name `blur`. This seems very specific to your use case. You could `$emit` an event instead and your settings using the `<url-field>` instance would need to register for that event and do what you need to do. An advantage doing this is your registered listener can also cancel the propagation. I think a more unique event name should also be used like `url-field-blur`.

**Comment by stulees** [comment]
@donnapep Also, question regarding that above code for `isImage` function, are you loading/displaying the image in the widget settings?

**Comment by donnapep** [comment]
@stulees Makes sense re: event name. I've updated it.

To confirm, `$emit` does not work. I believe that's because the component is using isolate scope and so they don't have share a parent/child relationship to allow this type of communication to work.

No, I'm not displaying the image, just validating it.

Thx.

**Comment by stulees** [comment]
@donnapep In my experience using `$emit` within a custom directive has worked. 

Google Drive Picker using `$emit` - http://goo.gl/oCNL2o

Google Spreadsheet Controls registering for the `picked` event that Google Drive Picker sent - http://goo.gl/KOEgmH

So the `isImage` function above is what you're using to validate that the url is an image, correct? To avoid this unnecessary async code, could you not use a regexp to check for an allowable file extension? I'm actually doing that right now with my work on Background Setting V2. I'm using this regex: 
```
/\.(gif|jpg|jpeg|tiff|png)$/i`
```

**Comment by donnapep** [comment]
@stulees Wow, magic. It actually worked this time. Thanks for that, although now I have no clue what those articles I just read were talking about.

**Comment by donnapep** [comment]
@stulees Re: file checking. That only checks the extension, not that the image actually exists at that URL.

**Comment by stulees** [comment]
@donnapep Okay good to hear. 

re: image checking, understood. Is that a requirement? Do you feel it's necessary? In Video Widget Settings, I am only validating the file extension. Any further "existence" checking I thought was unnecessary as that will be handled within the Widget itself. Let me know as this affects the Background Setting V2 component and potentially the Video Widget settings also. Thanks

**Comment by stulees** [comment]
@donnapep Oh and :+1: for this PR now

**Comment by donnapep** [comment]
@stulees I think that for video it would be overkill because you'd actually have to start downloading the video in order to validate it. For images that's not a problem and it's relatively fast. I would consider doing this in the background setting though in order to potentially eliminate some issues in the forum with people complaining that their images aren't showing up. And if that's the case I should probably put this code into some sort of image service so that we both can use it. Which repo do we put that type of stuff in?

**Comment by donnapep** [comment]
@stulees Also, you said you have some changes to the URL field coming? Should we wait to tag this repo until those changes are in as well?

**Comment by stulees** [comment]
@donnapep Yes an image validation service would be ideal. It should go in widget-settings-ui-core. You could either add it to `svc-common-settings` or create a new service. 

The changes to URL Field are referring to this card - http://goo.gl/jWJp35 I won't be working on them until after I finish with Background Setting V2. I think you could hold off tagging for now. Thanks

**Comment by donnapep** [comment]
@stulees nvm. Looks like I have to tag it in order to pull it in.

**Pull request merged**
