### PR TITLE
Integrating file-selector into background-image-setting

### PR DESCRIPTION
**Pull request by stulees**
- Replacing instance of `url-field` with `file-selector` in html template
- Ensuring storage folder button omitted from `file-selector` instance
- `selector` object replaces `url` property in directive defaults
- e2e tests revised and now ensuring a required default for `color` is applied in the e2e HTML file which was previously breaking the page

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep @rodrigopavezi Please review, thanks. As per the others, this PR will get rebased when the other PRs get merged first.

**Comment by donnapep** [comment]
:+1:

**Comment by rodrigopavezi** [comment]
@stulees looks good. I guess the editor app will have to use the selector object on the background data instead of the url value. :+1:

**Comment by stulees** [comment]
@rodrigopavezi That's correct, I will mention it in the release notes

**Pull request merged**
