### PR TITLE
Add "PUD Failover" setting to scroll

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees Please review. Thx.

**Comment by stulees** [comment]
@donnapep Will you be adding the tooltip in the Widget itself instead of this Scroll Setting component? was that intended?

**Comment by donnapep** [comment]
@stulees Nope, definitely not. Will fix. Thx!

**Comment by donnapep** [comment]
@stulees Added the tooltip.

In the Calendar Widget there is a tooltip beside Scroll Pause, but in the code for this component there is no tooltip. Do you know if it was removed at some point and the Widget just not rebuilt?

**Comment by stulees** [comment]
@donnapep Yes the Scroll setting underwent changes to conform to the new UX in this commit - https://github.com/Rise-Vision/widget-settings-ui-components/commit/15deb120e3a8facbbdadc95e10028128b02a9ee8 . This work was done when the RSS Widget was being worked on.

**Comment by stulees** [comment]
:+1: for the tooltip inclusion

**Comment by donnapep** [comment]
@stulees OK, thx.

**Pull request merged**
