### PR TITLE
Bower fix and Background Image Setting demo fix

### PR DESCRIPTION
**Pull request by stulees**
- bower updated to specify `#master` for `common-style`.
- Add missing dependencies in `background-image-setting` demo

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Please review, thanks

**Comment by donnapep** [comment]
@stulees OK, you're probably getting to be a pro at this now. What's the difference between specifying no tag and using #master?

**Comment by stulees** [comment]
@donnapep Not a pro by any means yet, but I have noticed a significant distinction in the name of the dependency compared to the name specified in the dependency bower file. If they're not the same, two packages get built. For example, it's happening in this repo. This repo states `common-style` as a dependency and prior to this PR, specified no tag or branch. The *actual* name of the dependency in its bower file is `rv-common-style`. So what happens is a `rv-common-style` package and a `common-style` package is being built in components/. `rv-common-style` package is the latest. `common-style` is depending on what other dependencies (who also incorrectly call it `common-style`) have specified and then a resolution is needed. 

If this is all confusing (which it is) lets discuss Thursday. What I'd like to do at some point is correct a lot of our repos to specify the *actual* name of the dependency as defined in its bower file. Then no more multiple packages will be created and we should be able to manage specifying tags/branches/none/resolutions more precisely across our repos.

**Comment by donnapep** [comment]
@stulees Wow, OK, I didn't know that made a difference. Thx. :+1:

**Pull request merged**
